/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commuterreservation;

import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Bram
 */
public class formDataKereta extends javax.swing.JFrame {
int Manggarai, Bekasi, Cikarang, Jatinegara, StasiunUI, Tebet, Depok, Bogor, Harga;

    /**
     * Creates new form formDataKereta
     */

    public formDataKereta() {
        initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manggarai = new javax.swing.JRadioButton();
        jatinegara = new javax.swing.JRadioButton();
        stasiun_ui = new javax.swing.JRadioButton();
        depok = new javax.swing.JRadioButton();
        tebet = new javax.swing.JRadioButton();
        bogor = new javax.swing.JRadioButton();
        cikarang = new javax.swing.JRadioButton();
        bekasi = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        hargatiket = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        KotaTujuan = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PT. K.A. SEJAHTERA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setName(""); // NOI18N

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Jenis");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Kota Tujuan");

        manggarai.setBackground(new java.awt.Color(204, 255, 204));
        manggarai.setText("Manggarai");
        manggarai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manggaraiActionPerformed(evt);
            }
        });

        jatinegara.setBackground(new java.awt.Color(204, 255, 204));
        jatinegara.setText("Jatinegara");
        jatinegara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jatinegaraActionPerformed(evt);
            }
        });

        stasiun_ui.setBackground(new java.awt.Color(204, 255, 204));
        stasiun_ui.setText("Stasiun UI");
        stasiun_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stasiun_uiActionPerformed(evt);
            }
        });

        depok.setBackground(new java.awt.Color(204, 255, 204));
        depok.setText("Depok");
        depok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depokActionPerformed(evt);
            }
        });

        tebet.setBackground(new java.awt.Color(204, 255, 204));
        tebet.setText("Tebet");
        tebet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tebetActionPerformed(evt);
            }
        });

        bogor.setBackground(new java.awt.Color(204, 255, 204));
        bogor.setText("Bogor");
        bogor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bogorActionPerformed(evt);
            }
        });

        cikarang.setBackground(new java.awt.Color(204, 255, 204));
        cikarang.setText("Cikarang");
        cikarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarangActionPerformed(evt);
            }
        });

        bekasi.setBackground(new java.awt.Color(204, 255, 204));
        bekasi.setText("Bekasi");
        bekasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bekasiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Harga Tiket");

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setText("Selanjutnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        KotaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Commuter Line"}));
        KotaTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotaTujuanActionPerformed(evt);
            }
        });

        jButton2.setText("KERETA BANDARA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(hargatiket, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cikarang)
                                    .addComponent(bekasi)
                                    .addComponent(KotaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manggarai)
                                    .addComponent(jatinegara))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tebet)
                                            .addComponent(bogor)
                                            .addComponent(stasiun_ui)
                                            .addComponent(depok)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(19, 19, 19)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(KotaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manggarai)
                    .addComponent(stasiun_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jatinegara)
                    .addComponent(depok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bekasi)
                    .addComponent(tebet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cikarang)
                    .addComponent(bogor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hargatiket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KotaTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotaTujuanActionPerformed
        
            String a = (String) KotaTujuan.getSelectedItem();
            keretabiasa Biasa = new keretabiasa();
            
            
        switch(a) {
            case "Pilih...":
                hargatiket.setText("");
                break;
                
            case "Commuter Line":
                int hargatiket1 = Biasa.harga();
                
                    Manggarai = 5000 + hargatiket1;
                    Jatinegara = 4000 + hargatiket1;
                    Bekasi = 4500 + hargatiket1;
                    Cikarang = 6000 + hargatiket1;
                    StasiunUI = 5000 + hargatiket1;
                    Tebet = 4000 + hargatiket1;
                    Bogor = 10000 + hargatiket1;
                    Depok = 7000 + hargatiket1;
                break;
            default:
            break;
        }
       
    }//GEN-LAST:event_KotaTujuanActionPerformed

    private void depokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depokActionPerformed
       if(depok.isSelected())
        jatinegara.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        
      
        {
           hargatiket.setText(String.valueOf(Depok));
        }
    }//GEN-LAST:event_depokActionPerformed

    private void bekasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bekasiActionPerformed
        if(bekasi.isSelected())
        jatinegara.setSelected(false);
        depok.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Bekasi));
        }
    }//GEN-LAST:event_bekasiActionPerformed

    private void jatinegaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jatinegaraActionPerformed
        if(jatinegara.isSelected())
        depok.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Jatinegara));
        } 
    }//GEN-LAST:event_jatinegaraActionPerformed

    private void cikarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarangActionPerformed
        if(cikarang.isSelected())
        jatinegara.setSelected(false);
        bekasi.setSelected(false);
        depok.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Cikarang));
        }
    }//GEN-LAST:event_cikarangActionPerformed

    private void manggaraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manggaraiActionPerformed
        if(manggarai.isSelected())
        depok.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        jatinegara.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Manggarai));
        } 
    }//GEN-LAST:event_manggaraiActionPerformed

    private void tebetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tebetActionPerformed
        if(tebet.isSelected())
        depok.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        jatinegara.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Tebet));
        } 
    }//GEN-LAST:event_tebetActionPerformed

    private void bogorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bogorActionPerformed
        if(bogor.isSelected())
        depok.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        jatinegara.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(Bogor));
        } 
    }//GEN-LAST:event_bogorActionPerformed

    private void stasiun_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stasiun_uiActionPerformed
        if(stasiun_ui.isSelected())
        depok.setSelected(false);
        bekasi.setSelected(false);
        cikarang.setSelected(false);
        tebet.setSelected(false);
        bogor.setSelected(false);
        stasiun_ui.setSelected(false);
        manggarai.setSelected(false);
        {
           hargatiket.setText(String.valueOf(StasiunUI));
        } 
    }//GEN-LAST:event_stasiun_uiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String jml = hargatiket.getText(); 
        new formCheckout(jml).setVisible(true);
            this.setVisible(false);
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new formKeretaBandara().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Yakin Anda Ingin LOGOUT?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
        if(n == JOptionPane.YES_OPTION){
            this.dispose();
            formLogin login = new formLogin();
            login.setVisible(true);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDataKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDataKereta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> KotaTujuan;
    private javax.swing.JRadioButton bekasi;
    private javax.swing.JRadioButton bogor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cikarang;
    private javax.swing.JRadioButton depok;
    private javax.swing.JTextField hargatiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jatinegara;
    private javax.swing.JRadioButton manggarai;
    private javax.swing.JRadioButton stasiun_ui;
    private javax.swing.JRadioButton tebet;
    // End of variables declaration//GEN-END:variables
}
